---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-trust-anchor
  namespace: kube-system
spec:
  ca:
    secretName: root-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: webhook-issuer
  namespace: kube-system
spec:
  ca:
    secretName: webhook-issuer-tls
