---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: root-trust-anchor
  namespace: cert-manager
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqakNDQVRPZ0F3SUJBZ0lRUVhBc052UTRJS3FVRExMSFczcno2VEFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTRNRFl3TXpVNQpNVEphRncwek16QTJNVFF3TXpVNU1USmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXdGT1BxQmNmZUl5NTdCbDgKTkQrTHczR0dBT0ZzVXlSY2RzNWV2Y3VIbU82azAyMzU1RHJGWXJtQUN3cVFFMjlsY3Z5TENzcUtVQmplQS82WQpWMmpwcEtORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRkVDSmcyVEhtYXc1bkEyQW5GNmVSYnNra09PQU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ3cKaDZ0bzhGU2w1MUNpWXF5akhhdmlsd1dnQmE3eHQ5eHNydUVsUWJ1bjRBSWhBTVJxaGxTNXZSWDA2ME43WnAvMwozZUpUU1ZIZ0ZXcmthOFp1Yi9jK0tJdDMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: >-
    LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJ6ZEJaeWNUTDFpYjdDOHV6eGx0cGU4L0FYYXkxRjhGa1VDanozd3Y0NVNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFd0ZPUHFCY2ZlSXk1N0JsOE5EK0x3M0dHQU9Gc1V5UmNkczVldmN1SG1PNmswMjM1NURyRgpZcm1BQ3dxUUUyOWxjdnlMQ3NxS1VCamVBLzZZVjJqcHBBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls
