---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lerero.lvh.me
  namespace: production
spec:
  secretName: lerero.lvh.me
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: root-trust-anchor
    kind: ClusterIssuer
  commonName: "lerero.lvh.me"
  dnsNames:
  - "lerero.lvh.me"
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: lerero.lvh.me
  namespace: production
spec:
  hostname: "lerero.lvh.me"
  tlsSecret:
    name: lerero.lvh.me
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: -1
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: lerero-http
  namespace: production
spec:
  port: 8080
  protocol: HTTPS  # NOT A TYPO, see below
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: lerero-https
  namespace: production
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: lerero.lvh.me
  namespace: production
spec:
  prefix: /
  rewrite: ""
  service: lerero:3000
  hostname: "lerero.lvh.me"
