apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: linkerd-crds
      version: '1.6.1'
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 1m
  targetNamespace: linkerd
