apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd-crds
  interval: 1h
  chart:
    spec:
      chart: linkerd-control-plane
      version: '1.12.6'
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 1m
  targetNamespace: linkerd
  values:
    podLabels:
      satria.shp/cluster-name: k3d-local
    policyValidator:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-policy-validator
    proxyInjector:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-proxy-injector
    profileValidator:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-sp-validator
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM

    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.crt
      targetPath: identity.issuer.tls.crtPEM

    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.key
      targetPath: identity.issuer.tls.keyPEM
