apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: emissary-ingress
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.5.3"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  targetNamespace: monitoring
  values:
    grafana:
      adminPassword: admin
    namespaceOverride: "monitoring"
