apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lerero
  namespace: flux-system
spec:
  dependsOn:
    - name: emissary-ingress
  interval: 10m0s
  path: ./manifests/deployments/lerero
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
